// Generated by CoffeeScript 1.7.1
(function() {
  var empty, error, line, redraw, remove, save;

  save = function(filer, db) {
    return filer.write('file.txt', {
      data: JSON.stringify(db),
      type: 'text/plain'
    });
  };

  redraw = function(filter, db) {
    var table;
    $('#content').empty();
    table = $('<table></table>');
    $.each(db, function(index, value) {
      var input, select, submit, tr;
      tr = $('<tr></tr>');
      select = $('<p>' + '</p>');
      input = $('<p>' + value['text'] + '</p>');
      submit = $("<p class='link' title='" + index + "'>Delete</p>");
      submit.click(function() {
        var ask;
        ask = window.confirm('Delete this?');
        if (ask) {
          return remove(filter, db, $(this).attr('title'));
        }
      });
      tr.append($('<td class="select"></td>').append(select));
      tr.append($('<td class="input"></td>').append(input));
      tr.append($('<td class="submit"></tr>').append(submit));
      return table.append(tr);
    });
    table.append(line(filter, db));
    $('#content').append(table);
    return window.scrollTo(0, document.body.scrollHeight);
  };

  line = function(filter, db) {
    var input, select, submit, tr;
    tr = $('<tr class="line"></tr>');
    select = $('<select></select>');
    select.append($('<option>Category</option>'));
    input = $('<input class="text" type="text"></input>');
    input.focus(function() {
      var dt;
      dt = new Date($.now());
      return $(this).attr('value', dt.getFullYear() + sprintf('.%02d.%02d, ', dt.getMonth(), dt.getDate()) + sprintf('%02d:%02d:%02d | ', dt.getHours(), dt.getMinutes(), dt.getSeconds()));
    });
    submit = $('<p class="link">Save</p>');
    submit.click(function() {
      if (input.val()) {
        db.push({
          'time': $.now(),
          'category': select.val(),
          'text': '' + input.val()
        });
        save(filter, db);
        return redraw(filter, db);
      }
    });
    input.keypress(function(e) {
      if (e.which === 13 && $(this).val()) {
        db.push({
          'time': $.now(),
          'category': select.val(),
          'text': '' + input.val()
        });
        save(filter, db);
        return redraw(filter, db);
      }
    });
    tr.append($('<td class="select"></td>').append(select));
    tr.append($('<td class="input"></td>').append(input));
    return tr.append($('<td class="submit"></td>').append(submit));
  };

  $(document).ready(function() {
    var filer;
    filer = new Filer();
    filer.init({
      persistent: true,
      size: 1024 * 1024
    }, function() {
      return filer.open('file.txt', function(file) {
        var reader;
        reader = new FileReader();
        reader.onload = function(e) {
          return redraw(filer, JSON.parse(reader.result));
        };
        return reader.readAsText(file);
      });
    });
    $('#close_link').click(function() {
      $('#popup_content').empty();
      return $('#popup').css('display', 'none');
    });
    $('#download_link').click(function() {
      var contents, copy;
      contents = $('#download_template').html();
      copy = $('<div id="download"></div>');
      $('#popup_content').empty();
      $('#popup_content').append(copy.append(contents));
      return $('#popup').css('display', 'block');
    });
    return $('#clear_link').click(function() {
      var ask;
      ask = window.confirm('Would you like to empty the scaffold?');
      if (ask) {
        return empty(filer);
      }
    });
  });

  remove = function(filer, db, index) {
    db.splice(index, 1);
    save(filer, db);
    return redraw(filer, db);
  };

  empty = function(filer) {
    save(filer, []);
    return redraw(filer, []);
  };

  error = function(e) {
    return console.log('Error' + e.name);
  };

}).call(this);
